spark:
  appName: HackathonSparkBatch
  master: local[*]
  options:
    spark.serializer: org.apache.spark.serializer.JavaSerializer
    spark.scheduler.mode: FAIR
    es.nodes: ldp-elastic-balancer-dev.lumeris.io
    es.net.http.auth.user: elastic
    es.net.http.auth.pass: changeme
 
defaults:
  exceptionHandler:
    type: SimpleExceptionHandler
  
spring:
  redis:
    cluster:
      nodes:
        - ldp-redis-balancer-dev.lumeris.io:6379
      
server:
    port: 8089
kafka:
  bootstrap-servers: 10.80.94.110:9092
  topic:
    hackathon: hackathon 

logging:
  level:
    com.lumeris.dataplatform: DEBUG
